on: push
name: test
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run tests for library
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        stable: false

    - name: run tests for cli
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        stable: false
      env:
        PROJECT_PATH: "./cli/synocrypto"
        CI: "true"